# Generated by Django 6.0.6 on 2026-06-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('badge', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
                ('current_status', models.CharField(max_length=300)),
                ('goal', models.TextField()),
                ('tech_stack', models.JSONField(default=dict)),
                ('email', models.EmailField(default='sufilldigital@gmail.com', max_length=254)),
                ('github', models.URLField(default='https://github.com/sufillxman')),
                ('linkedin', models.URLField(default='https://linkedin.com/in/sufill-x-man')),
                ('instagram', models.URLField(default='https://instagram.com/sufilldigital')),
                ('bio', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech', models.JSONField(default=list)),
                ('status', models.CharField(default='Active', max_length=100)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True, default='#')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
